apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
    visualize: 'true'
  name: customers-service
#  annotations:
#    auth.istio.io/8081: NONE
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
#  - name: http-management
#    port: 8081
#    targetPort: 8081
  selector:
    app: customers-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
    visualize: 'true'
  name: customers-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-service
      visualize: 'true'
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8081'
      labels:
        app: customers-service
        visualize: 'true'
    spec:
      volumes:
      - name: credentials
        secret:
          secretName: petclinic-credentials
      containers:
      - name: customers-service
        image: saturnism/gcp-spring-petclinic-customers-service:latest
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:8081/actuator/info
        livenessProbe:
          exec:
            command:
            - curl
            - http://localhost:8081/actuator/health
          initialDelaySeconds: 60
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 2000m
        volumeMounts:
        - name: credentials 
          mountPath: "/etc/credentials"
          readOnly: true
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: gcp,production
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/petclinic-service-account.json
        ports:
        - name: http
          containerPort: 8080
#        - name: http-management
#          containerPort: 8081
